
dist: trusty
sudo: required
language: fortran

script:
 - (cd build && cmake .. && make && ctest --output-on-failure)

matrix:
  include:
   - os: linux
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - gcc-8 gfortran-8
     install:
     before_install:
       - export FC=gfortran-8
